# Generated by Django 3.1.2 on 2021-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idexterno', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('tamano', models.IntegerField(default=0)),
                ('tipo', models.CharField(blank=True, choices=[('d', 'Digital'), ('f', 'Fisico')], default='d', max_length=1)),
                ('consola', models.CharField(blank=True, choices=[('nsw', 'SWITCH'), ('ps4', 'PS4')], max_length=3)),
                ('tiempo', models.IntegerField(default=0)),
                ('terminado', models.BooleanField(default=False)),
            ],
        ),
    ]
