# Generated by Django 3.1.2 on 2021-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_juego_idprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='image',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
