# Generated by Django 3.1.2 on 2021-06-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0007_auto_20210601_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(blank=True, choices=[('nsw', 'SWITCH'), ('ps4', 'PS4'), ('ps5', 'PS5')], max_length=3),
        ),
    ]
