# Generated by Django 3.1.2 on 2021-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0008_auto_20210608_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='estado',
            field=models.CharField(blank=True, choices=[('n', 'Nuevo'), ('u', 'Usado')], default='u', max_length=1),
        ),
    ]
