# Generated by Django 3.1.2 on 2021-06-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0009_juego_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(blank=True, choices=[('nsw', 'SWITCH'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('3ds', '3DS')], max_length=3),
        ),
    ]
