# Generated by Django 3.1.2 on 2021-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0010_auto_20210609_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pBase', models.FloatField(default=0.0)),
                ('dBase', models.FloatField(default=0.0)),
                ('detBase', models.CharField(max_length=200, null=True)),
                ('pYambalu', models.FloatField(default=0.0)),
                ('dYambalu', models.FloatField(default=0.0)),
                ('detYambalu', models.CharField(max_length=200, null=True)),
                ('consola', models.CharField(blank=True, choices=[('nsw', 'SWITCH'), ('ps4', 'PS4'), ('ps5', 'PS5')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=200, unique=True)),
                ('valor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
